import {
  StudentParentIcon,
  StudentTeacherIcon,
  MaleStudentIcon,
  FemaleStudentIcon,
} from "../../../assets/icons/students";

export const scoresheetData = [
  {
    id: 1,
    student_name: "Dory Maplethorpe",
    student_image: FemaleStudentIcon,
    dob: "19/09/2017",
    gender: "Female",
    religion: "Christianity",
    nationality: "Nigerian",
    state: "Kaduna",
    lga: "Chikun",
    average_score: "90%",
    school_fees: "PAID",
    class: "SS2",
    fullclass: "SS2",
    total_subjects: "07",
    section: "Secondary",
    teacher: {
      fullName: "Mary Sani",
      email: "sanim@gmail.com",
      contact: "08120205967",
      teacher_image: StudentTeacherIcon,
    },
    parent: {
      fullName: "Ann Itodo Ibrahim",
      email: "example@email.com",
      contact: "08120205967",
      address: "No 10, Independence Way, Kaduna",
      relationship: "Mother",
      occupation: "Civil Servant",
      religion: "Christianity",
      nationality: "Nigerian",
      state: "Kaduna",
      lga: "Chikun",
      parent_image: StudentParentIcon,
    },
    scoresheet: {
      testOne: 9,
      testTwo: 8,
      exams: 91,
      averageScore: "91%",
    },
  },
  {
    id: 2,
    student_name: "Tunde Bakare",
    student_image: MaleStudentIcon,
    dob: "04/12/2016",
    gender: "Male",
    religion: "Islam",
    nationality: "Nigerian",
    state: "Lagos",
    lga: "Ikeja",
    average_score: "75%",
    school_fees: "UNPAID",
    class: "SS1",
    fullclass: "SS1",
    total_subjects: "08",
    section: "Secondary",
    teacher: {
      fullName: "Ibrahim Musa",
      email: "ibrahim.m@gmail.com",
      contact: "08032215987",
      teacher_image: StudentTeacherIcon,
    },
    parent: {
      fullName: "Suleiman Bakare",
      email: "sulebak@gmail.com",
      contact: "08055677899",
      address: "No 22, Broad Street, Lagos",
      relationship: "Father",
      occupation: "Engineer",
      religion: "Islam",
      nationality: "Nigerian",
      state: "Lagos",
      lga: "Ikeja",
      parent_image: StudentParentIcon,
    },
    scoresheet: {
      testOne: 9,
      testTwo: 8,
      exams: 91,
      averageScore: "91%",
    },
  },
  {
    id: 3,
    student_name: "Fatima Sadiq",
    student_image: FemaleStudentIcon,
    dob: "15/02/2015",
    gender: "Female",
    religion: "Islam",
    nationality: "Nigerian",
    state: "Kano",
    lga: "Gwale",
    average_score: "80%",
    school_fees: "PAID",
    class: "Pri 6",
    fullclass: "Primary 6",
    total_subjects: "09",
    section: "Primary",
    teacher: {
      fullName: "Zainab Bello",
      email: "zbello@gmail.com",
      contact: "09012345678",
      teacher_image: StudentTeacherIcon,
    },
    parent: {
      fullName: "Ahmed Sadiq",
      email: "ahmedsadiq@gmail.com",
      contact: "09023456789",
      address: "No 5, Mallam Aminu Way, Kano",
      relationship: "Father",
      occupation: "Businessman",
      religion: "Islam",
      nationality: "Nigerian",
      state: "Kano",
      lga: "Gwale",
      parent_image: StudentParentIcon,
    },
    scoresheet: {
      testOne: 8,
      testTwo: 7,
      exams: 90,
      averageScore: "90%",
    },
  },
  {
    id: 4,
    student_name: "Emeka Okonkwo",
    student_image: MaleStudentIcon,
    dob: "23/06/2014",
    gender: "Male",
    religion: "Christianity",
    nationality: "Nigerian",
    state: "Anambra",
    lga: "Onitsha North",
    average_score: "92%",
    school_fees: "PAID",
    class: "Pri 5",
    fullclass: "Primary 5",
    total_subjects: "06",
    section: "Primary",
    teacher: {
      fullName: "Chinedu Eze",
      email: "ezechinedu@gmail.com",
      contact: "08090012345",
      teacher_image: StudentTeacherIcon,
    },
    parent: {
      fullName: "Ngozi Okonkwo",
      email: "ngozi.okonkwo@yahoo.com",
      contact: "08089090900",
      address: "No 3, Awka Road, Onitsha",
      relationship: "Mother",
      occupation: "Trader",
      religion: "Christianity",
      nationality: "Nigerian",
      state: "Anambra",
      lga: "Onitsha North",
      parent_image: StudentParentIcon,
    },
    scoresheet: {
      testOne: 9,
      testTwo: 6,
      exams: 96,
      averageScore: "96%",
    },
  },
  {
    id: 5,
    student_name: "Chinwe Uzo",
    student_image: FemaleStudentIcon,
    dob: "12/08/2016",
    gender: "Female",
    religion: "Christianity",
    nationality: "Nigerian",
    state: "Imo",
    lga: "Owerri",
    average_score: "85%",
    school_fees: "UNPAID",
    class: "SS2",
    fullclass: "SS2",
    total_subjects: "08",
    section: "Secondary",
    teacher: {
      fullName: "Emmanuel Kalu",
      email: "ekalu@gmail.com",
      contact: "07054321890",
      teacher_image: StudentTeacherIcon,
    },
    parent: {
      fullName: "Ogechi Uzo",
      email: "ogechiu@gmail.com",
      contact: "08076543210",
      address: "No 9, Egbu Road, Owerri",
      relationship: "Mother",
      occupation: "Nurse",
      religion: "Christianity",
      nationality: "Nigerian",
      state: "Imo",
      lga: "Owerri",
      parent_image: StudentParentIcon,
    },
    scoresheet: {
      testOne: 7,
      testTwo: 8,
      exams: 90,
      averageScore: "90%",
    },
  },
  {
    id: 6,
    student_name: "Abdulrahman Abubakar",
    student_image: MaleStudentIcon,
    dob: "01/01/2017",
    gender: "Male",
    religion: "Islam",
    nationality: "Nigerian",
    state: "Borno",
    lga: "Maiduguri",
    average_score: "88%",
    school_fees: "PAID",
    class: "Pri 5",
    fullclass: "Primary 5",
    total_subjects: "07",
    section: "Primary",
    teacher: {
      fullName: "Hauwa Bintu",
      email: "hauwab@gmail.com",
      contact: "09087654321",
      teacher_image: StudentTeacherIcon,
    },
    parent: {
      fullName: "Abubakar Ali",
      email: "abubakar.ali@gmail.com",
      contact: "09056789012",
      address: "No 7, Shehu Laminu Way, Maiduguri",
      relationship: "Father",
      occupation: "Farmer",
      religion: "Islam",
      nationality: "Nigerian",
      state: "Borno",
      lga: "Maiduguri",
      parent_image: StudentParentIcon,
    },
    scoresheet: {
      testOne: 5,
      testTwo: 6,
      exams: 82,
      averageScore: "82%",
    },
  },
  {
    id: 7,
    student_name: "Efe Oghenekaro",
    student_image: FemaleStudentIcon,
    dob: "17/11/2015",
    gender: "Female",
    religion: "Christianity",
    nationality: "Nigerian",
    state: "Delta",
    lga: "Warri South",
    average_score: "91%",
    school_fees: "PAID",
    class: "SS3",
    fullclass: "SS3",
    total_subjects: "09",
    section: "Secondary",
    teacher: {
      fullName: "Joseph Idibie",
      email: "josephidibie@yahoo.com",
      contact: "08012332100",
      teacher_image: StudentTeacherIcon,
    },
    parent: {
      fullName: "Oghenekaro Efe",
      email: "efe.oghenekaro@gmail.com",
      contact: "08087654321",
      address: "No 12, Ekpan Road, Warri",
      relationship: "Mother",
      occupation: "Trader",
      religion: "Christianity",
      nationality: "Nigerian",
      state: "Delta",
      lga: "Warri South",
      parent_image: StudentParentIcon,
    },
    scoresheet: {
      testOne: 7,
      testTwo: 9,
      exams: 10,
      averageScore: "10%",
    },
  },
];
