const studentsTableData = [
  {
    id: "1",
    student_name: "Dory Maplethorpe",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "2",
    student_name: "Corina Tyer",
    gender: "Female",
    class: "Class name",
    average_score: "81%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "3",
    student_name: "Morty Delort",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "4",
    student_name: "Stevy Kubacek",
    gender: "Male",
    class: "Class name",
    average_score: "91%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "5",
    student_name: "Brenna Valois",
    gender: "Female",
    class: "Class name",
    average_score: "87%",
    school_fees: "unpaid", 
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "6",
    student_name: "Cassandra Fesby",
    gender: "Female",
    class: "Class name",
    average_score: "84%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "7",
    student_name: "Donelle Backs",
    gender: "Female",
    class: "Class name",
    average_score: "87%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "8",
    student_name: "Marcie Douch",
    gender: "Female",
    class: "Class name",
    average_score: "80%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "9",
    student_name: "Otha Doring",
    gender: "Female",
    class: "Class name",
    average_score: "85%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "10",
    student_name: "Urbanus Croxley",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { avatar: "", fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "11",
    student_name: "Irving Gard",
    gender: "Male",
    class: "Class name",
    average_score: "80%",
    school_fees: "unpaid",
    parent: { avatar: "", fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "12",
    student_name: "Padraig Kinchin",
    gender: "Male",
    class: "Class name",
    average_score: "85%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "13",
    student_name: "Tandi Alexsandrovich",
    gender: "Female",
    class: "Class name",
    average_score: "86%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "14",
    student_name: "Cassandry Wildber",
    gender: "Female",
    class: "Class name",
    average_score: "85%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "15",
    student_name: "Aristotle Everal",
    gender: "Male",
    class: "Class name",
    average_score: "88%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
]

export default studentsTableData;