const studentsTableData = [
  {
    id: "1",
    student_name: "Dory Maplethorpe",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "2",
    student_name: "Corina Tyer",
    gender: "Female",
    class: "Class name",
    average_score: "81%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "3",
    student_name: "Morty Delort",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "4",
    student_name: "Stevy Kubacek",
    gender: "Male",
    class: "Class name",
    average_score: "91%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "5",
    student_name: "Brenna Valois",
    gender: "Female",
    class: "Class name",
    average_score: "87%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "6",
    student_name: "Cassandra Fesby",
    gender: "Female",
    class: "Class name",
    average_score: "84%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "7",
    student_name: "Donelle Backs",
    gender: "Female",
    class: "Class name",
    average_score: "87%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "8",
    student_name: "Marcie Douch",
    gender: "Female",
    class: "Class name",
    average_score: "80%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "9",
    student_name: "Otha Doring",
    gender: "Female",
    class: "Class name",
    average_score: "85%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "10",
    student_name: "Urbanus Croxley",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { avatar: "", fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "11",
    student_name: "Irving Gard",
    gender: "Male",
    class: "Class name",
    average_score: "80%",
    school_fees: "unpaid",
    parent: { avatar: "", fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "12",
    student_name: "Padraig Kinchin",
    gender: "Male",
    class: "Class name",
    average_score: "85%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "13",
    student_name: "Tandi Alexsandrovich",
    gender: "Female",
    class: "Class name",
    average_score: "86%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "14",
    student_name: "Cassandry Wildber",
    gender: "Female",
    class: "Class name",
    average_score: "85%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "15",
    student_name: "Aristotle Everal",
    gender: "Male",
    class: "Class name",
    average_score: "88%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "16",
    student_name: "Dory Maplethorpe",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "17",
    student_name: "Corina Tyer",
    gender: "Female",
    class: "Class name",
    average_score: "81%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "18",
    student_name: "Morty Delort",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "19",
    student_name: "Stevy Kubacek",
    gender: "Male",
    class: "Class name",
    average_score: "91%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "20",
    student_name: "Brenna Valois",
    gender: "Female",
    class: "Class name",
    average_score: "87%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "21",
    student_name: "Cassandra Fesby",
    gender: "Female",
    class: "Class name",
    average_score: "84%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "22",
    student_name: "Donelle Backs",
    gender: "Female",
    class: "Class name",
    average_score: "87%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "23",
    student_name: "Marcie Douch",
    gender: "Female",
    class: "Class name",
    average_score: "80%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "24",
    student_name: "Otha Doring",
    gender: "Female",
    class: "Class name",
    average_score: "85%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "25",
    student_name: "Urbanus Croxley",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { avatar: "", fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "26",
    student_name: "Irving Gard",
    gender: "Male",
    class: "Class name",
    average_score: "80%",
    school_fees: "unpaid",
    parent: { avatar: "", fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "27",
    student_name: "Padraig Kinchin",
    gender: "Male",
    class: "Class name",
    average_score: "85%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "28",
    student_name: "Tandi Alexsandrovich",
    gender: "Female",
    class: "Class name",
    average_score: "86%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "29",
    student_name: "Cassandry Wildber",
    gender: "Female",
    class: "Class name",
    average_score: "85%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "30",
    student_name: "Aristotle Everal",
    gender: "Male",
    class: "Class name",
    average_score: "88%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "31",
    student_name: "Dory Maplethorpe",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "32",
    student_name: "Corina Tyer",
    gender: "Female",
    class: "Class name",
    average_score: "81%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "33",
    student_name: "Morty Delort",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "34",
    student_name: "Stevy Kubacek",
    gender: "Male",
    class: "Class name",
    average_score: "91%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "35",
    student_name: "Brenna Valois",
    gender: "Female",
    class: "Class name",
    average_score: "87%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "36",
    student_name: "Cassandra Fesby",
    gender: "Female",
    class: "Class name",
    average_score: "84%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "37",
    student_name: "Donelle Backs",
    gender: "Female",
    class: "Class name",
    average_score: "87%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "38",
    student_name: "Marcie Douch",
    gender: "Female",
    class: "Class name",
    average_score: "80%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "39",
    student_name: "Otha Doring",
    gender: "Female",
    class: "Class name",
    average_score: "85%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "40",
    student_name: "Urbanus Croxley",
    gender: "Male",
    class: "Class name",
    average_score: "90%",
    school_fees: "paid",
    parent: { avatar: "", fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "41",
    student_name: "Irving Gard",
    gender: "Male",
    class: "Class name",
    average_score: "80%",
    school_fees: "unpaid",
    parent: { avatar: "", fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "42",
    student_name: "Padraig Kinchin",
    gender: "Male",
    class: "Class name",
    average_score: "85%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "43",
    student_name: "Tandi Alexsandrovich",
    gender: "Female",
    class: "Class name",
    average_score: "86%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "44",
    student_name: "Cassandry Wildber",
    gender: "Female",
    class: "Class name",
    average_score: "85%",
    school_fees: "unpaid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
  {
    id: "45",
    student_name: "Aristotle Everal",
    gender: "Male",
    class: "Class name",
    average_score: "88%",
    school_fees: "paid",
    parent: { fullName: "Ann Itodo Ibrahim", email: "example@email.com", contact: "08120205967" },
  },
]

export default studentsTableData;